services:
  be:
    build: ./be
    container_name: backend
    volumes:
      - ./be:/usr/src/app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - ./be/.env
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=weather_app
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./db_mongo:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin      
      - ME_CONFIG_BASICAUTH_PASSWORD=admin 
    ports:
      - "8081:8081"
